---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: myapp-db-secret
  namespace: myapp
spec:
  encryptedData:
    DB_PASSWORD: AgDAURyNCe2lUs+5wbDm6qhvZpvZz9xVHhR4069VdVzByGPZ/vK4iYQcPrVZi1RIJAMYQ8TBSWg6kf6UgAdyxiYOL9axbmh8YqXT+FmJAavAGP0Ou4CEBlgGoLRcNjgchIqSE9wBcSrR3W/tzWqk1FYDgosaYV9Vlz10ur2i3rAPigRisOK2Q5M3lhmyf7QrroPdTnE2vTkNVSH0Ouu5wbdjmbf2qf2ObMTEbjXGlv1mFkba/XrI2wZdw5WYteMIyYFmbuzyRjDzxZCbtJLpPntXHplzWjWgWgX0V0/mPhAREfqOH6x8A89MXMWbfU6lImk5gEejvCHuKerbkRxynlzg5RfpomLWhcdTdxFVBzvSy+sLlt0sqofy5fVs8vZgRU4zHRhmr41cCX5ugxYzCeDgO3YWR3MUq/zhpPHjbUFLNOaBn15G09JNyQKZFJnhmL/Mecs2feFq4zhG7D2NakziVEsJp9iSuGAg/+WIms8Z59DW1AMtYM+Mhuv+s42oxXi7gbrZ6NDJBXavkwm/9Qq0Y5FYSdxJIWH9ZNldLtMvWrTYCHUdeEl7iaD7iddT30VR7hTlHYcwICWr9SqdDjqDnjY7NAqq+qKa+v34CfF2h4Vr4tfy1dOlsA6VlLH4gci4Jlf5X3OA/XxJ7tTMqVXbS4wYHNovmgC0pxGHwgkgiX+O5dNY9dmNfociyw6xdJCc3aPotZ3s0KG9pNAi7AU=
  template:
    metadata:
      name: myapp-db-secret
      namespace: myapp
